### ISSUE TITLE
NoClassDefFound when showing the view

### ISSUE THREAD

**Issue by samthiriot** [samthiriot/knime-shapefiles-as-WKT#23]
`Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: View instantiation failed: null
	at org.knime.core.node.Node.getView(Node.java:1890)
	at org.knime.core.node.workflow.NativeNodeContainer.getNodeView(NativeNodeContainer.java:274)
	at org.knime.core.node.workflow.NodeContainer.getView(NodeContainer.java:1142)
	at org.knime.workbench.editor2.actions.OpenViewAction.lambda$0(OpenViewAction.java:127)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ExceptionInInitializerError
	at org.geotools.swing.tool.PanTool.<clinit>(PanTool.java:39)
	at ch.res_ear.samthiriot.knime.shapefilesAsWKT.view.DisplaySpatialPopulationNodeView.<init>(DisplaySpatialPopulationNodeView.java:97)
	at ch.res_ear.samthiriot.knime.shapefilesAsWKT.view.DisplaySpatialPopulationNodeFactory.createNodeView(DisplaySpatialPopulationNodeFactory.java:38)
	at ch.res_ear.samthiriot.knime.shapefilesAsWKT.view.DisplaySpatialPopulationNodeFactory.createNodeView(DisplaySpatialPopulationNodeFactory.java:1)
	at org.knime.core.node.NodeFactory.createAbstractNodeView(NodeFactory.java:543)
	at org.knime.core.node.Node.getView(Node.java:1886)
	... 17 more
Caused by: java.lang.IllegalArgumentException: Invalid directory path: bundleresource:/1259.fwk1625676573:30/org/geotools/swing/locale
	at org.geotools.swing.locale.PropertiesFileFinder.getAsLocalDir(PropertiesFileFinder.java:150)
	at org.geotools.swing.locale.PropertiesFileFinder.scan(PropertiesFileFinder.java:77)
	at org.geotools.swing.locale.LocaleUtils.loadLocaleInfo(LocaleUtils.java:280)
	at org.geotools.swing.locale.LocaleUtils.<clinit>(LocaleUtils.java:115)
	... 23 more`

**Comment by samthiriot** [comment]
The error appears because the geotool resources are available in the form of a resource shared from an osgi bundle (thus the "bundle://" uri). Yet the geotools library uses as dedicated class `PropertiesFileFinder` in order to find resources; this class only deals with jar (when the url ends with jar) or assumes the url is a directory. But in practice this is not a directory, it is a bundle:// url. 

ref
[1] http://docs.geotools.org/latest/userguide/welcome/application.html

**Comment by samthiriot** [comment]
double check packaging: http://docs.geotools.org/latest/userguide.old/welcome/application.html

**Comment by samthiriot** [comment]
see bug here: https://osgeo-org.atlassian.net/projects/GEOT/issues/GEOT-6290?filter=allopenissues

**Comment by samthiriot** [comment]
proposed a pull request to integrate our solution inside geotools
https://github.com/geotools/geotools/pull/2366

**Comment by samthiriot** [comment]
fixed in the geotools snapshot 22 branch.
